"""Topic 4: standalone approach comparison and risk-register generator."""
from __future__ import annotations
import csv,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]; OUT=ROOT/"Outputs"/"Day 4"/"Topic 4"
def write(name,rows,fields):
    with (OUT/name).open("w",newline="",encoding="utf-8-sig") as f:w=csv.DictWriter(f,fieldnames=fields);w.writeheader();w.writerows(rows)
def main():
    OUT.mkdir(parents=True,exist_ok=True)
    approaches=[{"approach":"Deterministic Python assistant","reliability":"High for validated structured inputs","determinism":"High","complexity":"Low MVP / medium integration","ui_fragility":"Low without UI control","governance":"Clear auditable rules","recommendation":"SELECT: compare and draft; preserve human approval"},{"approach":"RPA/UI automation","reliability":"Medium","determinism":"Medium","complexity":"Medium","ui_fragility":"High","governance":"Requires credential and change controls","recommendation":"Defer: selectors, authentication and safe submission are unverified"},{"approach":"AI agent","reliability":"Variable","determinism":"Low for judgement","complexity":"Medium-high","ui_fragility":"Medium-high","governance":"Needs evaluation, prompt/data controls and approval gate","recommendation":"Defer core decision; consider later for unstructured extraction"},{"approach":"Workflow/orchestration platform","reliability":"High after integration","determinism":"High","complexity":"High initial","ui_fragility":"Low with APIs","governance":"Needs system ownership and API design","recommendation":"Future phase after source-system access and ownership are agreed"}]
    write("approach_comparison.csv",approaches,["approach","reliability","determinism","complexity","ui_fragility","governance","recommendation"])
    risks=[{"risk":"Workflow meaning is inferred","likelihood":"High","impact":"High","evidence_reason":"Dataset B has no ground truth; BPROC labels are behavioral","mitigation":"Validate workflow with Finance users and sample cases","residual_risk":"Medium"},{"risk":"Incorrect or stale reference data","likelihood":"Medium","impact":"High","evidence_reason":"Logs do not identify authoritative reference source","mitigation":"Owned source, versioning, reconciliation and audit log","residual_risk":"Medium"},{"risk":"UI automation breaks","likelihood":"High","impact":"Medium","evidence_reason":"Browser/desktop UI controls may change","mitigation":"No UI submission in MVP; prefer API integration","residual_risk":"Low for MVP"},{"risk":"Exception handled as a match","likelihood":"Medium","impact":"High","evidence_reason":"Logs cannot reveal all business rules","mitigation":"Fail closed; discrepancy hold and human approval","residual_risk":"Medium"},{"risk":"Overstated value","likelihood":"Medium","impact":"Medium","evidence_reason":"Test timings and fragmented segments are not production execution measures","mitigation":"No time saving claim; pilot measurement after deployment","residual_risk":"Low"}]
    write("risk_register.csv",risks,["risk","likelihood","impact","evidence_reason","mitigation","residual_risk"])
    recommendation={"selected":"Deterministic Python assistant","why":"It is auditable and testable for structured comparisons, with no claim that it can infer business judgement or safely submit transactions.","rejected_or_deferred":{"RPA/UI automation":"UI and permissions are unvalidated; high fragility.","AI agent":"not needed for deterministic comparison and adds non-determinism.","Workflow/orchestration":"valuable after source/API ownership and integration design exist."},"approval_boundary":"Employee reviews all outputs and completes final registration."}
    (OUT/"approach_recommendation.json").write_text(json.dumps(recommendation,ensure_ascii=False,indent=2),encoding="utf-8")
    (OUT/"risk_approach_analysis.md").write_text("# Topic 4 — Risks and approaches\n\nSelect a deterministic, human-in-the-loop assistant for the MVP. It provides the most auditable path for structured comparison, while RPA, an AI agent, and a workflow platform are deferred until system access, business rules, and governance have been validated. See the CSV risk register for mitigations.\n",encoding="utf-8")
    print(f"Topic 4 complete: {len(approaches)} approaches and {len(risks)} risks")
if __name__=="__main__":main()
